# Generated by Django 5.2.1 on 2025-05-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_discount_tax_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', 'Рубль'), ('usd', 'Доллар')], default='rub', max_length=3),
        ),
    ]
